{
  "nodes": [
    {
      "id": "0",
      "type": "VoronoiNoiseNode",
      "title": "Voronoi",
      "x": -500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "cells": 128,
        "seed": 5,
        "invert": false
      },
      "promoted_fields": [
        "seed",
        "cells"
      ]
    },
    {
      "id": "1",
      "type": "InvertNode",
      "title": "Invert",
      "x": -100.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "FloodFillNode",
      "title": "Flood Fill",
      "x": 100.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "threshold": 0.5,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "FloodFillToGreyscaleNode",
      "title": "Flood Fill to Greyscale",
      "x": 300.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -700.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int",
        "default_value": 0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -700.0,
      "y": -140.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Cells",
        "data_type": "int",
        "default_value": 128
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "EdgeDetectNode",
      "title": "Edge Detect",
      "x": -300.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "standard_node_library\\subgraphs\\edge_detect.cg",
        "Input": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": [
        "Input"
      ]
    }
  ],
  "wires": [
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Input"
    },
    {
      "source_node": "5",
      "source_port": "Cells",
      "target_node": "0",
      "target_port": "cells"
    },
    {
      "source_node": "4",
      "source_port": "Seed",
      "target_node": "0",
      "target_port": "seed"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "Flood Fill"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Input"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "Output"
    }
  ]
}