{
  "nodes": [
    {
      "id": "0",
      "type": "VoronoiNoiseNode",
      "title": "Voronoi",
      "x": -500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "cells": 128,
        "seed": 5,
        "invert": false
      },
      "promoted_fields": [
        "seed",
        "cells"
      ]
    },
    {
      "id": "1",
      "type": "InvertNode",
      "title": "Invert",
      "x": 100.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "FloodFillNode",
      "title": "Flood Fill",
      "x": 300.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "threshold": 0.5,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "FloodFillToGreyscaleNode",
      "title": "Flood Fill to Greyscale",
      "x": 500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -700.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int",
        "default_value": 0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -700.0,
      "y": -140.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Cells",
        "data_type": "int",
        "default_value": 120
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 900.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "GradientNode",
      "title": "Gradient",
      "x": 300.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "color_a": [
          10,
          10,
          10,
          255
        ],
        "color_b": [
          255,
          255,
          255,
          255
        ],
        "angle": 90.0
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "CeilNode",
      "title": "Ceil",
      "x": 700.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "EdgeDetectNode",
      "title": "Edge Detect",
      "x": -100.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "standard_node_library\\subgraphs\\edge_detect.cg",
        "Input": [
          255,
          255,
          255,
          255
        ],
        "Thickness": 2.0
      },
      "promoted_fields": [
        "Input",
        "Thickness"
      ]
    },
    {
      "id": "10",
      "type": "IntToFloatNode",
      "title": "Int to Float",
      "x": -500.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "DivideNode",
      "title": "Divide",
      "x": -300.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "FloatNode",
      "title": "Float",
      "x": -500.0,
      "y": 40.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 30.0
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "Greyscale"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Thickness"
    },
    {
      "source_node": "5",
      "source_port": "Cells",
      "target_node": "10",
      "target_port": "Input"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "B"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "A"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "Output"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Input"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "Flood Fill"
    },
    {
      "source_node": "4",
      "source_port": "Seed",
      "target_node": "0",
      "target_port": "seed"
    },
    {
      "source_node": "5",
      "source_port": "Cells",
      "target_node": "0",
      "target_port": "cells"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Input"
    }
  ]
}