{
  "nodes": [
    {
      "id": "0",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -100.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Levels",
        "data_type": "int",
        "default_value": 6
      },
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "WhiteNoiseNode",
      "title": "White Noise",
      "x": 300.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0
      },
      "promoted_fields": [
        "seed"
      ]
    },
    {
      "id": "2",
      "type": "FractalSumBaseNode",
      "title": "Fractal Sum Base",
      "x": 300.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "C:\\git\\catena\\plugins\\noise_pack_01\\subgraphs\\fractal_sum_base.cg",
        "Levels": null,
        "Seed": 4
      },
      "promoted_fields": [
        "Levels",
        "Seed"
      ]
    },
    {
      "id": "3",
      "type": "IntegerNode",
      "title": "Integer",
      "x": -100.0,
      "y": 20.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 4
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -100.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int",
        "default_value": 0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "AddNode",
      "title": "Add",
      "x": 100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "int"
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 500.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "AddNode",
      "title": "Add",
      "x": 900.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "AddNode",
      "title": "Add",
      "x": 1300.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 1100.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 135.0,
        "scale_x": 1.4,
        "scale_y": 1.4
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 700.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 315.0,
        "scale_x": 1.4,
        "scale_y": 1.4
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 1500.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 1700.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "12",
      "target_port": "Output"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Seed"
    },
    {
      "source_node": "0",
      "source_port": "Levels",
      "target_node": "2",
      "target_port": "Levels"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "seed"
    },
    {
      "source_node": "4",
      "source_port": "Seed",
      "target_node": "5",
      "target_port": "A"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "B"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "A"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "B"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "A"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "A"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "B"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "Input"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "B"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Input"
    }
  ]
}