{
  "nodes": [
    {
      "id": "0",
      "type": "FractalSumBaseNode",
      "title": "Fractal Sum Base",
      "x": -600.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "C:\\git\\catena\\plugins\\noise_pack_01\\subgraphs\\fractal_sum_base.cg",
        "Levels": 0,
        "Seed": 0
      },
      "promoted_fields": [
        "Levels",
        "Seed"
      ]
    },
    {
      "id": "1",
      "type": "WhiteNoiseNode",
      "title": "White Noise",
      "x": -600.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0
      },
      "promoted_fields": [
        "seed"
      ]
    },
    {
      "id": "2",
      "type": "LevelsNode",
      "title": "Levels",
      "x": -400.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 240,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "BlurNode",
      "title": "Blur",
      "x": -200.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 4.0
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "BlurNode",
      "title": "Blur",
      "x": -200.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 2.0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 200.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "OffsetNode",
      "title": "Offset",
      "x": -200.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "offset_x": 1024,
        "offset_y": 1024,
        "wrap": true
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 600.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "LevelsNode",
      "title": "Levels",
      "x": -400.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 100,
        "input_high": 150,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "AddNode",
      "title": "Add",
      "x": 0.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 400.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1000.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 800.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 135.0,
        "scale_x": 1.4,
        "scale_y": 1.4
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 1200.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -1000.0,
      "y": -80.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int",
        "default_value": 0
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "IntegerNode",
      "title": "Integer",
      "x": -1000.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 14
      },
      "promoted_fields": []
    },
    {
      "id": "16",
      "type": "AddNode",
      "title": "Add",
      "x": -800.0,
      "y": -80.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "int"
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "seed"
    },
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "0",
      "target_port": "Seed"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "16",
      "target_port": "B"
    },
    {
      "source_node": "14",
      "source_port": "Seed",
      "target_node": "16",
      "target_port": "A"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "Input"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Top"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "12",
      "target_port": "Input"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Bottom"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Top"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "B"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "A"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Top"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "B"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "A"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "Input"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Bottom"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "Input"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Bottom"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Input"
    }
  ]
}