{
  "nodes": [
    {
      "id": "0",
      "type": "WhiteNoiseNode",
      "title": "White Noise",
      "x": -300.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0
      },
      "promoted_fields": [
        "seed"
      ]
    },
    {
      "id": "1",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 0.0,
        "scale_x": 200.0,
        "scale_y": 200.0
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 45.0,
        "scale_x": 150.0,
        "scale_y": 150.0
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 90.0,
        "scale_x": 100.0,
        "scale_y": 100.0
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 32.0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 32.0
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 32.0
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": -60.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 60.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 16.0
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 180.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "16",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 8.0
      },
      "promoted_fields": []
    },
    {
      "id": "17",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "18",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 900.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "19",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 920.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 50,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "20",
      "type": "RerouteNode",
      "title": "",
      "x": 0.0,
      "y": 940.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "21",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 4.0
      },
      "promoted_fields": []
    },
    {
      "id": "22",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "23",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "24",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 135.0,
        "scale_x": 50.0,
        "scale_y": 50.0
      },
      "promoted_fields": []
    },
    {
      "id": "25",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 180.0,
        "scale_x": 25.0,
        "scale_y": 25.0
      },
      "promoted_fields": []
    },
    {
      "id": "26",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 225.0,
        "scale_x": 12.5,
        "scale_y": 12.5
      },
      "promoted_fields": []
    },
    {
      "id": "27",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1900.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 50,
        "output_high": 200,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "28",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "29",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -500.0,
      "y": 1140.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Levels",
        "data_type": "int",
        "default_value": 9
      },
      "promoted_fields": []
    },
    {
      "id": "30",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "31",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 20.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 1
      },
      "promoted_fields": []
    },
    {
      "id": "32",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 20.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "33",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 600.0,
      "y": 1140.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 6
      },
      "promoted_fields": [
        "value"
      ]
    },
    {
      "id": "34",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 520.0,
      "y": 1100.0,
      "width": 280,
      "height": 100,
      "fields": {
        "label": "Default Index",
        "color": [
          80,
          80,
          40,
          180
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "35",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "36",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "37",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 160.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "38",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 160.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 2
      },
      "promoted_fields": []
    },
    {
      "id": "39",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 40.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "40",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 120.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "41",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 240.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "42",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 160.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "43",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 280.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 3
      },
      "promoted_fields": []
    },
    {
      "id": "44",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 280.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "45",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 220.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "46",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "47",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 1000.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "48",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 340.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "49",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 480.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "50",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "51",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 380.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "52",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 520.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 5
      },
      "promoted_fields": []
    },
    {
      "id": "53",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 520.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "54",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 380.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 4
      },
      "promoted_fields": []
    },
    {
      "id": "55",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 1000.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 9
      },
      "promoted_fields": []
    },
    {
      "id": "56",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 460.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "57",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 280.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "58",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 960.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "59",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 360.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "60",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 940.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "61",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 1700.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "62",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 900.0,
      "y": -140.0,
      "width": 700,
      "height": 1240,
      "fields": {
        "label": "Levels selection switch",
        "color": [
          38,
          80,
          76,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "63",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -40.0,
      "y": -140.0,
      "width": 840,
      "height": 1240,
      "fields": {
        "label": "Levels generation",
        "color": [
          77,
          42,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "64",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 2100.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "65",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -500.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int",
        "default_value": 0
      },
      "promoted_fields": []
    },
    {
      "id": "66",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 540.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "67",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 540.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 260.0,
        "scale_x": 6.0,
        "scale_y": 6.0
      },
      "promoted_fields": []
    },
    {
      "id": "68",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 540.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 4.0
      },
      "promoted_fields": []
    },
    {
      "id": "69",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 540.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "70",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "71",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 640.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 6
      },
      "promoted_fields": []
    },
    {
      "id": "72",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 580.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "73",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 640.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "74",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 520.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "75",
      "type": "ClampNode",
      "title": "Clamp",
      "x": -300.0,
      "y": 1140.0,
      "width": null,
      "height": null,
      "fields": {
        "minimum": 0.0,
        "maximum": 9.0,
        "data_type": "int"
      },
      "promoted_fields": []
    },
    {
      "id": "76",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 660.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "77",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "78",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 660.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 4.0
      },
      "promoted_fields": []
    },
    {
      "id": "79",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 720.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "80",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 7
      },
      "promoted_fields": []
    },
    {
      "id": "81",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 700.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "82",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 660.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "83",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 660.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 305.0,
        "scale_x": 3.0,
        "scale_y": 3.0
      },
      "promoted_fields": []
    },
    {
      "id": "84",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 640.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "85",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 400.0,
      "y": 780.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 25,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "86",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "87",
      "type": "BlurNode",
      "title": "Blur",
      "x": 200.0,
      "y": 780.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 4.0
      },
      "promoted_fields": []
    },
    {
      "id": "88",
      "type": "ComparisonNode",
      "title": "Comparison",
      "x": 1200.0,
      "y": 840.0,
      "width": null,
      "height": null,
      "fields": {
        "comparison_type": "Greater Than Or Equal"
      },
      "promoted_fields": []
    },
    {
      "id": "89",
      "type": "IntegerNode",
      "title": "Integer",
      "x": 920.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 8
      },
      "promoted_fields": []
    },
    {
      "id": "90",
      "type": "IntToVec4Node",
      "title": "Int to Vec4",
      "x": 1040.0,
      "y": 820.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "91",
      "type": "AddNode",
      "title": "Add",
      "x": 600.0,
      "y": 780.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "92",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 0.0,
      "y": 780.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 340.0,
        "scale_x": 1.5,
        "scale_y": 1.5
      },
      "promoted_fields": []
    },
    {
      "id": "93",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1400.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "81",
      "target_port": "Input"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "90",
      "target_port": "Input"
    },
    {
      "source_node": "91",
      "source_port": "Output",
      "target_node": "18",
      "target_port": "A"
    },
    {
      "source_node": "82",
      "source_port": "Output",
      "target_node": "91",
      "target_port": "A"
    },
    {
      "source_node": "69",
      "source_port": "Output",
      "target_node": "82",
      "target_port": "A"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "92",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "83",
      "target_port": "Input"
    },
    {
      "source_node": "93",
      "source_port": "Output",
      "target_node": "46",
      "target_port": "Bottom"
    },
    {
      "source_node": "84",
      "source_port": "Output",
      "target_node": "93",
      "target_port": "Bottom"
    },
    {
      "source_node": "74",
      "source_port": "Output",
      "target_node": "84",
      "target_port": "Bottom"
    },
    {
      "source_node": "87",
      "source_port": "Output",
      "target_node": "85",
      "target_port": "Input"
    },
    {
      "source_node": "85",
      "source_port": "Output",
      "target_node": "91",
      "target_port": "B"
    },
    {
      "source_node": "92",
      "source_port": "Output",
      "target_node": "87",
      "target_port": "Input"
    },
    {
      "source_node": "88",
      "source_port": "Result",
      "target_node": "93",
      "target_port": "Alpha"
    },
    {
      "source_node": "86",
      "source_port": "Output",
      "target_node": "88",
      "target_port": "B"
    },
    {
      "source_node": "90",
      "source_port": "Output",
      "target_node": "88",
      "target_port": "A"
    },
    {
      "source_node": "89",
      "source_port": "Output",
      "target_node": "86",
      "target_port": "Input"
    },
    {
      "source_node": "91",
      "source_port": "Output",
      "target_node": "93",
      "target_port": "Top"
    },
    {
      "source_node": "78",
      "source_port": "Output",
      "target_node": "76",
      "target_port": "Input"
    },
    {
      "source_node": "76",
      "source_port": "Output",
      "target_node": "82",
      "target_port": "B"
    },
    {
      "source_node": "83",
      "source_port": "Output",
      "target_node": "78",
      "target_port": "Input"
    },
    {
      "source_node": "79",
      "source_port": "Result",
      "target_node": "84",
      "target_port": "Alpha"
    },
    {
      "source_node": "77",
      "source_port": "Output",
      "target_node": "79",
      "target_port": "B"
    },
    {
      "source_node": "81",
      "source_port": "Output",
      "target_node": "79",
      "target_port": "A"
    },
    {
      "source_node": "80",
      "source_port": "Output",
      "target_node": "77",
      "target_port": "Input"
    },
    {
      "source_node": "82",
      "source_port": "Output",
      "target_node": "84",
      "target_port": "Top"
    },
    {
      "source_node": "75",
      "source_port": "Output",
      "target_node": "33",
      "target_port": "value"
    },
    {
      "source_node": "29",
      "source_port": "Levels",
      "target_node": "75",
      "target_port": "Input"
    },
    {
      "source_node": "23",
      "source_port": "Output",
      "target_node": "69",
      "target_port": "A"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "72",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "67",
      "target_port": "Input"
    },
    {
      "source_node": "69",
      "source_port": "Output",
      "target_node": "74",
      "target_port": "Top"
    },
    {
      "source_node": "50",
      "source_port": "Output",
      "target_node": "74",
      "target_port": "Bottom"
    },
    {
      "source_node": "71",
      "source_port": "Output",
      "target_node": "73",
      "target_port": "Input"
    },
    {
      "source_node": "72",
      "source_port": "Output",
      "target_node": "70",
      "target_port": "A"
    },
    {
      "source_node": "73",
      "source_port": "Output",
      "target_node": "70",
      "target_port": "B"
    },
    {
      "source_node": "70",
      "source_port": "Result",
      "target_node": "74",
      "target_port": "Alpha"
    },
    {
      "source_node": "67",
      "source_port": "Output",
      "target_node": "68",
      "target_port": "Input"
    },
    {
      "source_node": "66",
      "source_port": "Output",
      "target_node": "69",
      "target_port": "B"
    },
    {
      "source_node": "68",
      "source_port": "Output",
      "target_node": "66",
      "target_port": "Input"
    },
    {
      "source_node": "65",
      "source_port": "Seed",
      "target_node": "0",
      "target_port": "seed"
    },
    {
      "source_node": "61",
      "source_port": "Output",
      "target_node": "27",
      "target_port": "Input"
    },
    {
      "source_node": "46",
      "source_port": "Output",
      "target_node": "61",
      "target_port": "Input"
    },
    {
      "source_node": "18",
      "source_port": "Output",
      "target_node": "46",
      "target_port": "Top"
    },
    {
      "source_node": "23",
      "source_port": "Output",
      "target_node": "50",
      "target_port": "Top"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "57",
      "target_port": "Top"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "60",
      "target_port": "Input"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "56",
      "target_port": "Input"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "48",
      "target_port": "Input"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "45",
      "target_port": "Input"
    },
    {
      "source_node": "42",
      "source_port": "Output",
      "target_node": "57",
      "target_port": "Bottom"
    },
    {
      "source_node": "54",
      "source_port": "Output",
      "target_node": "51",
      "target_port": "Input"
    },
    {
      "source_node": "48",
      "source_port": "Output",
      "target_node": "59",
      "target_port": "A"
    },
    {
      "source_node": "51",
      "source_port": "Output",
      "target_node": "59",
      "target_port": "B"
    },
    {
      "source_node": "59",
      "source_port": "Result",
      "target_node": "57",
      "target_port": "Alpha"
    },
    {
      "source_node": "49",
      "source_port": "Result",
      "target_node": "50",
      "target_port": "Alpha"
    },
    {
      "source_node": "53",
      "source_port": "Output",
      "target_node": "49",
      "target_port": "B"
    },
    {
      "source_node": "56",
      "source_port": "Output",
      "target_node": "49",
      "target_port": "A"
    },
    {
      "source_node": "52",
      "source_port": "Output",
      "target_node": "53",
      "target_port": "Input"
    },
    {
      "source_node": "57",
      "source_port": "Output",
      "target_node": "50",
      "target_port": "Bottom"
    },
    {
      "source_node": "55",
      "source_port": "Output",
      "target_node": "47",
      "target_port": "Input"
    },
    {
      "source_node": "60",
      "source_port": "Output",
      "target_node": "58",
      "target_port": "A"
    },
    {
      "source_node": "47",
      "source_port": "Output",
      "target_node": "58",
      "target_port": "B"
    },
    {
      "source_node": "58",
      "source_port": "Result",
      "target_node": "46",
      "target_port": "Alpha"
    },
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "42",
      "target_port": "Top"
    },
    {
      "source_node": "39",
      "source_port": "Output",
      "target_node": "42",
      "target_port": "Bottom"
    },
    {
      "source_node": "41",
      "source_port": "Result",
      "target_node": "42",
      "target_port": "Alpha"
    },
    {
      "source_node": "44",
      "source_port": "Output",
      "target_node": "41",
      "target_port": "B"
    },
    {
      "source_node": "45",
      "source_port": "Output",
      "target_node": "41",
      "target_port": "A"
    },
    {
      "source_node": "43",
      "source_port": "Output",
      "target_node": "44",
      "target_port": "Input"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "39",
      "target_port": "Top"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "35",
      "target_port": "Top"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "35",
      "target_port": "Bottom"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "36",
      "target_port": "Input"
    },
    {
      "source_node": "35",
      "source_port": "Output",
      "target_node": "39",
      "target_port": "Bottom"
    },
    {
      "source_node": "38",
      "source_port": "Output",
      "target_node": "37",
      "target_port": "Input"
    },
    {
      "source_node": "36",
      "source_port": "Output",
      "target_node": "40",
      "target_port": "A"
    },
    {
      "source_node": "37",
      "source_port": "Output",
      "target_node": "40",
      "target_port": "B"
    },
    {
      "source_node": "40",
      "source_port": "Result",
      "target_node": "39",
      "target_port": "Alpha"
    },
    {
      "source_node": "28",
      "source_port": "Result",
      "target_node": "35",
      "target_port": "Alpha"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "30",
      "target_port": "Input"
    },
    {
      "source_node": "32",
      "source_port": "Output",
      "target_node": "28",
      "target_port": "B"
    },
    {
      "source_node": "30",
      "source_port": "Output",
      "target_node": "28",
      "target_port": "A"
    },
    {
      "source_node": "31",
      "source_port": "Output",
      "target_node": "32",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "Input"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Input"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "Input"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Input"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "Input"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "A"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "B"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "A"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "B"
    },
    {
      "source_node": "13",
      "source_port": "Output",
      "target_node": "12",
      "target_port": "Input"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "A"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "B"
    },
    {
      "source_node": "17",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "B"
    },
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "17",
      "target_port": "Input"
    },
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "A"
    },
    {
      "source_node": "19",
      "source_port": "Output",
      "target_node": "18",
      "target_port": "B"
    },
    {
      "source_node": "20",
      "source_port": "",
      "target_node": "19",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "20",
      "target_port": ""
    },
    {
      "source_node": "21",
      "source_port": "Output",
      "target_node": "22",
      "target_port": "Input"
    },
    {
      "source_node": "22",
      "source_port": "Output",
      "target_node": "23",
      "target_port": "B"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "23",
      "target_port": "A"
    },
    {
      "source_node": "24",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "Input"
    },
    {
      "source_node": "25",
      "source_port": "Output",
      "target_node": "16",
      "target_port": "Input"
    },
    {
      "source_node": "26",
      "source_port": "Output",
      "target_node": "21",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "24",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "25",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "26",
      "target_port": "Input"
    },
    {
      "source_node": "27",
      "source_port": "Output",
      "target_node": "64",
      "target_port": "Output"
    }
  ]
}