{
  "nodes": [
    {
      "id": "0",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 500.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 100,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 900.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "ColorNode",
      "title": "Color",
      "x": 500.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          109,
          109,
          109,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 700.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 500.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 100,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "InvertNode",
      "title": "Invert",
      "x": 500.0,
      "y": -220.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 700.0,
      "y": -220.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 900.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1100.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1300.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 30,
        "output_low": 30,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "ShapeNode",
      "title": "Shape",
      "x": -200.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Paraboloid",
        "size": 1.0,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "ScatterNode",
      "title": "Scatter",
      "x": 100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "count": 50,
        "scale": 0.2,
        "scale_variance": 1.0,
        "rotation_variance": 0.0,
        "seed": 123
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 1500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -400.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int",
        "default_value": 0
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "OffsetNode",
      "title": "Offset",
      "x": 100.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "offset_x": 50.0,
        "offset_y": 50.0,
        "wrap": true
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "PerlinNoiseNode",
      "title": "Perlin Noise",
      "x": -200.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 256.0,
        "octaves": 4,
        "seed": 0
      },
      "promoted_fields": [
        "seed"
      ]
    },
    {
      "id": "16",
      "type": "ScatterNode",
      "title": "Scatter",
      "x": 100.0,
      "y": -220.0,
      "width": null,
      "height": null,
      "fields": {
        "count": 60,
        "scale": 0.2,
        "scale_variance": 1.0,
        "rotation_variance": 0.0,
        "seed": 2
      },
      "promoted_fields": [
        "seed"
      ]
    },
    {
      "id": "17",
      "type": "WarpNode",
      "title": "Warp",
      "x": 300.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 50.0,
        "direction": 270.0
      },
      "promoted_fields": []
    },
    {
      "id": "18",
      "type": "WarpNode",
      "title": "Warp",
      "x": 300.0,
      "y": -220.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 50.0,
        "direction": 90.0
      },
      "promoted_fields": []
    },
    {
      "id": "19",
      "type": "RerouteNode",
      "title": "",
      "x": 240.0,
      "y": -280.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "19",
      "source_port": "",
      "target_node": "17",
      "target_port": "Displacement"
    },
    {
      "source_node": "19",
      "source_port": "",
      "target_node": "18",
      "target_port": "Displacement"
    },
    {
      "source_node": "19",
      "source_port": "",
      "target_node": "4",
      "target_port": "Input"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "19",
      "target_port": ""
    },
    {
      "source_node": "18",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Input"
    },
    {
      "source_node": "17",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "B"
    },
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "0",
      "target_port": "Input"
    },
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "18",
      "target_port": "Input"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "17",
      "target_port": "Input"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Input"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "B"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "A"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Bottom"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Top"
    },
    {
      "source_node": "2",
      "source_port": "Color",
      "target_node": "6",
      "target_port": "B"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "A"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Top"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Bottom"
    },
    {
      "source_node": "2",
      "source_port": "Color",
      "target_node": "3",
      "target_port": "A"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "12",
      "target_port": "Output"
    },
    {
      "source_node": "13",
      "source_port": "Seed",
      "target_node": "15",
      "target_port": "seed"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "Input"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "16",
      "target_port": "Input"
    },
    {
      "source_node": "13",
      "source_port": "Seed",
      "target_node": "16",
      "target_port": "seed"
    }
  ]
}