{
  "nodes": [
    {
      "id": "0",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 300.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 100,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 800.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.4
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "ColorNode",
      "title": "Color",
      "x": 300.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          109,
          109,
          109,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 500.0,
      "y": -20.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 300.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 100,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "CloudsNode",
      "title": "Clouds",
      "x": -100.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 96.0,
        "octaves": 5,
        "persistence": 0.6,
        "contrast": 1.5,
        "seed": 4
      },
      "promoted_fields": [
        "seed"
      ]
    },
    {
      "id": "6",
      "type": "InvertNode",
      "title": "Invert",
      "x": 300.0,
      "y": -220.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 500.0,
      "y": -220.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 800.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.8
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1000.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1200.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 30,
        "output_low": 30,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "ShapeNode",
      "title": "Shape",
      "x": -100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Paraboloid",
        "size": 1.0,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "ScatterNode",
      "title": "Scatter",
      "x": 100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "count": 60,
        "scale": 0.2,
        "scale_variance": 1.0,
        "rotation_variance": 0.0,
        "seed": 1
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 1400.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -300.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Seed",
        "data_type": "int"
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "OffsetNode",
      "title": "Offset",
      "x": 100.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "offset_x": 512,
        "offset_y": 512,
        "wrap": true
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "0",
      "target_port": "Input"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "Input"
    },
    {
      "source_node": "14",
      "source_port": "Seed",
      "target_node": "5",
      "target_port": "seed"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "12",
      "target_port": "Input"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "B"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "A"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "Bottom"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "Top"
    },
    {
      "source_node": "2",
      "source_port": "Color",
      "target_node": "7",
      "target_port": "B"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "A"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "Input"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Top"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Bottom"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "Input"
    },
    {
      "source_node": "2",
      "source_port": "Color",
      "target_node": "3",
      "target_port": "A"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "B"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "Output"
    }
  ]
}