{
  "nodes": [
    {
      "id": "0",
      "type": "ShapeNode",
      "title": "Shape",
      "x": -2100.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Square",
        "size": 0.95,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "TileNode",
      "title": "Tile",
      "x": -1700.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "tiles_x": 4,
        "tiles_y": 4
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "BevelNode",
      "title": "Bevel",
      "x": -1900.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "distance": 20.0,
        "depth": 1.0,
        "soft": false
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "FloodFillNode",
      "title": "Flood Fill",
      "x": -1000.0,
      "y": 260.0,
      "width": null,
      "height": null,
      "fields": {
        "threshold": 0.5,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "LevelsNode",
      "title": "Levels",
      "x": -1500.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 50,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "RoundNode",
      "title": "Round",
      "x": -1300.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "InvertNode",
      "title": "Invert",
      "x": -1000.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "SlopeBlurNode",
      "title": "Slope Blur",
      "x": 100.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "samples": 8,
        "intensity": 4.0,
        "mode": "Blur"
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "PerlinNoiseNode",
      "title": "Perlin Noise",
      "x": -500.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 128.0,
        "octaves": 4,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "DirectionalWarpNode",
      "title": "Directional Warp",
      "x": -100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 200.0,
        "direction": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "HistogramScanNode",
      "title": "Histogram Scan",
      "x": -300.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "position": 0.85,
        "contrast": 0.3
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -1540.0,
      "y": 460.0,
      "width": 740,
      "height": 140,
      "fields": {
        "label": "Ground Edge Mask",
        "color": [
          80,
          80,
          40,
          180
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -540.0,
      "y": -120.0,
      "width": 840,
      "height": 300,
      "fields": {
        "label": "Edge Damage",
        "color": [
          80,
          80,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -1040.0,
      "y": 200.0,
      "width": 640,
      "height": 240,
      "fields": {
        "label": "Random Tile ID",
        "color": [
          40,
          80,
          71,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "FloodFillToRandomColorNode",
      "title": "Flood Fill to Random Color",
      "x": -800.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "BreakOutNode",
      "title": "Break Out",
      "x": -600.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "standard_node_library\\subgraphs\\break_out.cg",
        "Input": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": [
        "Input"
      ]
    },
    {
      "id": "16",
      "type": "VoronoiNoiseNode",
      "title": "Voronoi",
      "x": -1700.0,
      "y": 1100.0,
      "width": null,
      "height": null,
      "fields": {
        "cells": 320,
        "seed": 0,
        "invert": false
      },
      "promoted_fields": []
    },
    {
      "id": "17",
      "type": "EdgeDetectNode",
      "title": "Edge Detect",
      "x": -1500.0,
      "y": 1100.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "standard_node_library\\subgraphs\\edge_detect.cg",
        "Input": [
          255,
          255,
          255,
          255
        ],
        "Thickness": 2.0
      },
      "promoted_fields": [
        "Input",
        "Thickness"
      ]
    },
    {
      "id": "18",
      "type": "InvertNode",
      "title": "Invert",
      "x": -1300.0,
      "y": 1100.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "19",
      "type": "VectorWarpNode",
      "title": "Vector Warp",
      "x": -1100.0,
      "y": 1100.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 15.0
      },
      "promoted_fields": []
    },
    {
      "id": "20",
      "type": "PerlinNoiseNode",
      "title": "Perlin Noise",
      "x": -1300.0,
      "y": 900.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 128.0,
        "octaves": 4,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "21",
      "type": "VoronoiNoiseNode",
      "title": "Voronoi",
      "x": -1700.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "cells": 80,
        "seed": 2,
        "invert": false
      },
      "promoted_fields": []
    },
    {
      "id": "22",
      "type": "InvertNode",
      "title": "Invert",
      "x": -1300.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "23",
      "type": "VectorWarpNode",
      "title": "Vector Warp",
      "x": -1100.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 15.0
      },
      "promoted_fields": []
    },
    {
      "id": "24",
      "type": "EdgeDetectNode",
      "title": "Edge Detect",
      "x": -1500.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "standard_node_library\\subgraphs\\edge_detect.cg",
        "Input": [
          255,
          255,
          255,
          255
        ],
        "Thickness": 2.0
      },
      "promoted_fields": [
        "Input",
        "Thickness"
      ]
    },
    {
      "id": "25",
      "type": "FloodFillNode",
      "title": "Flood Fill",
      "x": -900.0,
      "y": 1000.0,
      "width": null,
      "height": null,
      "fields": {
        "threshold": 0.5,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "26",
      "type": "HistogramScanNode",
      "title": "Histogram Scan",
      "x": -500.0,
      "y": 1000.0,
      "width": null,
      "height": null,
      "fields": {
        "position": 1.0,
        "contrast": 0.3
      },
      "promoted_fields": []
    },
    {
      "id": "27",
      "type": "CeilNode",
      "title": "Ceil",
      "x": -300.0,
      "y": 1000.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "28",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": -100.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "29",
      "type": "RerouteNode",
      "title": "",
      "x": -200.0,
      "y": 900.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "30",
      "type": "RerouteNode",
      "title": "",
      "x": -900.0,
      "y": 900.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "31",
      "type": "FloodFillToBBoxNode",
      "title": "Flood Fill to BBox Size",
      "x": -700.0,
      "y": 1000.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "32",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -1740.0,
      "y": 760.0,
      "width": 1840,
      "height": 540,
      "fields": {
        "label": "Cracks Mask Generation",
        "color": [
          73,
          36,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "33",
      "type": "VectorWarpNode",
      "title": "Vector Warp",
      "x": 800.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 200.0
      },
      "promoted_fields": []
    },
    {
      "id": "34",
      "type": "RoundNode",
      "title": "Round",
      "x": 900.0,
      "y": 320.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "35",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 700.0,
      "y": 320.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 200,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "36",
      "type": "ColorNode",
      "title": "Color",
      "x": 1300.0,
      "y": 660.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "37",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1500.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "38",
      "type": "AddNode",
      "title": "Add",
      "x": 1300.0,
      "y": 320.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "39",
      "type": "RerouteNode",
      "title": "",
      "x": 1240.0,
      "y": 520.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "40",
      "type": "InvertNode",
      "title": "Invert",
      "x": 1100.0,
      "y": 320.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "41",
      "type": "BevelNode",
      "title": "Bevel",
      "x": 1700.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "distance": 3.0,
        "depth": 1.0,
        "soft": false
      },
      "promoted_fields": []
    },
    {
      "id": "42",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 2100.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "43",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 2300.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "44",
      "type": "RerouteNode",
      "title": "",
      "x": 1800.0,
      "y": -80.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "45",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 660.0,
      "y": 280.0,
      "width": 2040,
      "height": 460,
      "fields": {
        "label": "Cracks Integration",
        "color": [
          80,
          38,
          39,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "46",
      "type": "FloodFillToGradientNode",
      "title": "Flood Fill to Gradient",
      "x": -800.0,
      "y": 220.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0,
        "direction_seed": 5.8
      },
      "promoted_fields": []
    },
    {
      "id": "47",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 400.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "48",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 600.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.4
      },
      "promoted_fields": []
    },
    {
      "id": "49",
      "type": "RerouteNode",
      "title": "",
      "x": 280.0,
      "y": 240.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "50",
      "type": "RerouteNode",
      "title": "",
      "x": -300.0,
      "y": 680.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "51",
      "type": "FloodFillNode",
      "title": "Flood Fill",
      "x": 200.0,
      "y": 860.0,
      "width": null,
      "height": null,
      "fields": {
        "threshold": 0.5,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "52",
      "type": "FloodFillToGradientNode",
      "title": "Flood Fill to Gradient",
      "x": 400.0,
      "y": 860.0,
      "width": null,
      "height": null,
      "fields": {
        "seed": 0,
        "direction_seed": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "53",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 600.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "54",
      "type": "VectorWarpNode",
      "title": "Vector Warp",
      "x": 800.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 200.0
      },
      "promoted_fields": []
    },
    {
      "id": "55",
      "type": "RerouteNode",
      "title": "",
      "x": 200.0,
      "y": 620.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "56",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1700.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "57",
      "type": "ColorNode",
      "title": "Color",
      "x": 1540.0,
      "y": 880.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "58",
      "type": "RerouteNode",
      "title": "",
      "x": 700.0,
      "y": 680.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "59",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1900.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "60",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 180.0,
      "y": 740.0,
      "width": 1720.0,
      "height": 220.0,
      "fields": {
        "label": "Fracture Height",
        "color": [
          47,
          80,
          38,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "61",
      "type": "RerouteNode",
      "title": "",
      "x": 2000.0,
      "y": 520.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "62",
      "type": "MoistureNoiseNode",
      "title": "Moisture Noise",
      "x": -600.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "noise_pack_01\\subgraphs\\moisture_noise.cg",
        "Seed": 3264
      },
      "promoted_fields": [
        "Seed"
      ]
    },
    {
      "id": "63",
      "type": "PerlinNoiseNode",
      "title": "Perlin Noise",
      "x": -600.0,
      "y": 1500.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 128.0,
        "octaves": 4,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "64",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": -400.0,
      "y": 1460.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "65",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": -200.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "66",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 0.0,
      "y": 1460.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "67",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 200.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "68",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1000.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.6
      },
      "promoted_fields": []
    },
    {
      "id": "69",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 800.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "70",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -640.0,
      "y": 1360.0,
      "width": 1240,
      "height": 340,
      "fields": {
        "label": "Surface Imperfections",
        "color": [
          29,
          49,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "71",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1100.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "72",
      "type": "FractalSumBaseNode",
      "title": "Fractal Sum Base",
      "x": -200.0,
      "y": 1600.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "noise_pack_01\\subgraphs\\fractal_sum_base.cg",
        "Levels": 6,
        "Seed": 0
      },
      "promoted_fields": [
        "Levels",
        "Seed"
      ]
    },
    {
      "id": "73",
      "type": "HSVNode",
      "title": "HSV",
      "x": 1300.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "hue_shift": 0,
        "saturation": 1.0,
        "value": 6.0
      },
      "promoted_fields": []
    },
    {
      "id": "74",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1500.0,
      "y": 800.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 255,
        "gamma": 4.0
      },
      "promoted_fields": []
    },
    {
      "id": "75",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 2500.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "76",
      "type": "RerouteNode",
      "title": "",
      "x": -200.0,
      "y": 320.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "77",
      "type": "VectorWarpNode",
      "title": "Vector Warp",
      "x": 400.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 200.0
      },
      "promoted_fields": []
    },
    {
      "id": "78",
      "type": "RerouteNode",
      "title": "",
      "x": 200.0,
      "y": 340.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "79",
      "type": "WriteNode",
      "title": "Height Output",
      "x": 5100.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {
        "texture_type": "Height",
        "filepath": "",
        "file_type": "PNG"
      },
      "promoted_fields": []
    },
    {
      "id": "80",
      "type": "WriteNode",
      "title": "AO Output",
      "x": 5100.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "texture_type": "AO",
        "filepath": "",
        "file_type": "PNG"
      },
      "promoted_fields": []
    },
    {
      "id": "81",
      "type": "WriteNode",
      "title": "Normal Output",
      "x": 5100.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {
        "texture_type": "Normal",
        "filepath": "",
        "file_type": "PNG"
      },
      "promoted_fields": []
    },
    {
      "id": "82",
      "type": "HeightToNormalNode",
      "title": "Height to Normal",
      "x": 4400.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 10.0,
        "space": "DirectX"
      },
      "promoted_fields": []
    },
    {
      "id": "83",
      "type": "RerouteNode",
      "title": "",
      "x": 4280.0,
      "y": 520.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "84",
      "type": "FractalSumBaseNode",
      "title": "Fractal Sum Base",
      "x": 2900.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "noise_pack_01\\subgraphs\\fractal_sum_base.cg",
        "Levels": 9,
        "Seed": 0
      },
      "promoted_fields": [
        "Levels",
        "Seed"
      ]
    },
    {
      "id": "85",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 3100.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "86",
      "type": "RerouteNode",
      "title": "",
      "x": 1400.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "87",
      "type": "RerouteNode",
      "title": "",
      "x": 2400.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "88",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 3300.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "89",
      "type": "RerouteNode",
      "title": "",
      "x": 3240.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "90",
      "type": "ShapeNode",
      "title": "Shape",
      "x": 1500.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Square",
        "size": 1.0,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "91",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": 1700.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 0.0,
        "scale_x": 1.0,
        "scale_y": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "92",
      "type": "TileNode",
      "title": "Tile",
      "x": 1900.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "tiles_x": 1,
        "tiles_y": 40
      },
      "promoted_fields": []
    },
    {
      "id": "93",
      "type": "BevelNode",
      "title": "Bevel",
      "x": 2100.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "distance": 15.0,
        "depth": 1.0,
        "soft": false
      },
      "promoted_fields": []
    },
    {
      "id": "94",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 2300.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "95",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 2500.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 20,
        "input_high": 255,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "96",
      "type": "WarpNode",
      "title": "Warp",
      "x": 2700.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 200.0,
        "direction": 270.0
      },
      "promoted_fields": []
    },
    {
      "id": "97",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 2900.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "98",
      "type": "RerouteNode",
      "title": "",
      "x": 3040.0,
      "y": 760.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "99",
      "type": "InvertNode",
      "title": "Invert",
      "x": 2600.0,
      "y": 1200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "100",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 3100.0,
      "y": 1400.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "101",
      "type": "RerouteNode",
      "title": "",
      "x": 3020.0,
      "y": 1620.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "102",
      "type": "RerouteNode",
      "title": "",
      "x": 1000.0,
      "y": 1420.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "103",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 700.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 225,
        "input_high": 255,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "104",
      "type": "CeilNode",
      "title": "Ceil",
      "x": 900.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "105",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 3700.0,
      "y": 500.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "106",
      "type": "RerouteNode",
      "title": "",
      "x": 3300.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "107",
      "type": "BevelNode",
      "title": "Bevel",
      "x": 2900.0,
      "y": 1200.0,
      "width": null,
      "height": null,
      "fields": {
        "distance": 10.0,
        "depth": 1.0,
        "soft": true
      },
      "promoted_fields": []
    },
    {
      "id": "108",
      "type": "InvertNode",
      "title": "Invert",
      "x": 3100.0,
      "y": 1200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "109",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 3300.0,
      "y": 1200.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "110",
      "type": "WriteNode",
      "title": "Albedo Output",
      "x": 5100.0,
      "y": 1600.0,
      "width": null,
      "height": null,
      "fields": {
        "texture_type": "Albedo",
        "filepath": "",
        "file_type": "PNG"
      },
      "promoted_fields": []
    },
    {
      "id": "111",
      "type": "RerouteNode",
      "title": "",
      "x": 700.0,
      "y": 1580.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "112",
      "type": "RerouteNode",
      "title": "",
      "x": 2640.0,
      "y": 1580.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "113",
      "type": "RerouteNode",
      "title": "",
      "x": 500.0,
      "y": 380.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "114",
      "type": "RerouteNode",
      "title": "",
      "x": 500.0,
      "y": 340.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "115",
      "type": "RerouteNode",
      "title": "",
      "x": 500.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "116",
      "type": "RerouteNode",
      "title": "",
      "x": 900.0,
      "y": 1920.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "117",
      "type": "ColorNode",
      "title": "Color",
      "x": 960.0,
      "y": 2020.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          153,
          255,
          213,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "118",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1300.0,
      "y": 1900.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "119",
      "type": "InvertNode",
      "title": "Invert",
      "x": 900.0,
      "y": 2200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "120",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1300.0,
      "y": 2200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "121",
      "type": "ColorNode",
      "title": "Color",
      "x": 900.0,
      "y": 2300.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          255,
          209,
          157,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "122",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 2000.0,
      "y": 1900.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "123",
      "type": "FractalSumBaseNode",
      "title": "Fractal Sum Base",
      "x": 900.0,
      "y": 2360.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "noise_pack_01\\subgraphs\\fractal_sum_base.cg",
        "Levels": 9,
        "Seed": 0
      },
      "promoted_fields": [
        "Levels",
        "Seed"
      ]
    },
    {
      "id": "124",
      "type": "FractalSum3Node",
      "title": "Fractal Sum 3",
      "x": 1300.0,
      "y": 2100.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "noise_pack_01\\subgraphs\\fractal_sum_3.cg",
        "Seed": 0
      },
      "promoted_fields": [
        "Seed"
      ]
    },
    {
      "id": "125",
      "type": "ColorNode",
      "title": "Color",
      "x": 1300.0,
      "y": 2000.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          76,
          62,
          47,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "126",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1720.0,
      "y": 1900.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 0.4
      },
      "promoted_fields": []
    },
    {
      "id": "127",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1500.0,
      "y": 2000.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "128",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 1700.0,
      "y": 2200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "129",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1500.0,
      "y": 2260.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 100,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "130",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1100.0,
      "y": 2300.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "131",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1100.0,
      "y": 2020.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "132",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 2200.0,
      "y": 1900.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "133",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 4700.0,
      "y": 1600.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "134",
      "type": "Vec4ToAONode",
      "title": "Vec4 to AO",
      "x": 4400.0,
      "y": 600.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 1.0,
        "samples": 4
      },
      "promoted_fields": []
    },
    {
      "id": "135",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 4100.0,
      "y": 1900.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "136",
      "type": "RerouteNode",
      "title": "",
      "x": 4000.0,
      "y": 2000.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "137",
      "type": "ColorNode",
      "title": "Color",
      "x": 4700.0,
      "y": 700.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          0,
          0,
          0,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "138",
      "type": "WriteNode",
      "title": "Metallic Output",
      "x": 5100.0,
      "y": 700.0,
      "width": null,
      "height": null,
      "fields": {
        "texture_type": "Metallic",
        "filepath": "",
        "file_type": "PNG"
      },
      "promoted_fields": []
    },
    {
      "id": "139",
      "type": "WriteNode",
      "title": "Roughness Output",
      "x": 5100.0,
      "y": 2400.0,
      "width": null,
      "height": null,
      "fields": {
        "texture_type": "Roughness",
        "filepath": "",
        "file_type": "PNG"
      },
      "promoted_fields": []
    },
    {
      "id": "140",
      "type": "ColorNode",
      "title": "Color",
      "x": 4100.0,
      "y": 2400.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          117,
          117,
          117,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "141",
      "type": "AddNode",
      "title": "Add",
      "x": 3500.0,
      "y": 2600.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "142",
      "type": "ColorNode",
      "title": "Color",
      "x": 4340.0,
      "y": 2500.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "143",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 4600.0,
      "y": 2400.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "144",
      "type": "MoistureNoiseNode",
      "title": "Moisture Noise",
      "x": 4100.0,
      "y": 2520.0,
      "width": null,
      "height": null,
      "fields": {
        "filepath": "noise_pack_01\\subgraphs\\moisture_noise.cg",
        "Seed": 0
      },
      "promoted_fields": [
        "Seed"
      ]
    },
    {
      "id": "145",
      "type": "ColorNode",
      "title": "Color",
      "x": 4100.0,
      "y": 2460.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          103,
          103,
          103,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "146",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 4300.0,
      "y": 2400.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "147",
      "type": "RerouteNode",
      "title": "",
      "x": 300.0,
      "y": 2720.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "148",
      "type": "InvertNode",
      "title": "Invert",
      "x": 3500.0,
      "y": 2700.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "149",
      "type": "AddNode",
      "title": "Add",
      "x": 3700.0,
      "y": 2600.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "150",
      "type": "RerouteNode",
      "title": "",
      "x": 4500.0,
      "y": 2620.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "151",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 860.0,
      "y": 1840.0,
      "width": 1540,
      "height": 660,
      "fields": {
        "label": "Color",
        "color": [
          80,
          80,
          40,
          180
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "152",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 3440.0,
      "y": 2360.0,
      "width": 1360,
      "height": 440,
      "fields": {
        "label": "Roughness",
        "color": [
          80,
          42,
          9,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "153",
      "type": "RerouteNode",
      "title": "",
      "x": 2500.0,
      "y": 2000.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "154",
      "type": "RerouteNode",
      "title": "",
      "x": 2300.0,
      "y": 2380.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "155",
      "type": "RerouteNode",
      "title": "",
      "x": 800.0,
      "y": 1680.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "156",
      "type": "RerouteNode",
      "title": "",
      "x": 1900.0,
      "y": 1680.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "157",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 1460.0,
      "y": 1160.0,
      "width": 2040,
      "height": 520,
      "fields": {
        "label": "Grout",
        "color": [
          73,
          72,
          79,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "158",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": 5060.0,
      "y": 340.0,
      "width": 240,
      "height": 1360,
      "fields": {
        "label": "Outputs",
        "color": [
          11,
          11,
          11,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "159",
      "type": "RerouteNode",
      "title": "",
      "x": 1640.0,
      "y": 2120.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "160",
      "type": "RerouteNode",
      "title": "",
      "x": 3600.0,
      "y": 420.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "160",
      "source_port": "",
      "target_node": "105",
      "target_port": "Alpha"
    },
    {
      "source_node": "106",
      "source_port": "",
      "target_node": "160",
      "target_port": ""
    },
    {
      "source_node": "28",
      "source_port": "Output",
      "target_node": "147",
      "target_port": ""
    },
    {
      "source_node": "146",
      "source_port": "Output",
      "target_node": "143",
      "target_port": "Bottom"
    },
    {
      "source_node": "144",
      "source_port": "Output",
      "target_node": "146",
      "target_port": "Alpha"
    },
    {
      "source_node": "145",
      "source_port": "Color",
      "target_node": "146",
      "target_port": "Top"
    },
    {
      "source_node": "140",
      "source_port": "Color",
      "target_node": "146",
      "target_port": "Bottom"
    },
    {
      "source_node": "142",
      "source_port": "Color",
      "target_node": "143",
      "target_port": "Top"
    },
    {
      "source_node": "143",
      "source_port": "Output",
      "target_node": "139",
      "target_port": "Input"
    },
    {
      "source_node": "89",
      "source_port": "",
      "target_node": "141",
      "target_port": "B"
    },
    {
      "source_node": "106",
      "source_port": "",
      "target_node": "141",
      "target_port": "A"
    },
    {
      "source_node": "137",
      "source_port": "Color",
      "target_node": "138",
      "target_port": "Input"
    },
    {
      "source_node": "136",
      "source_port": "",
      "target_node": "135",
      "target_port": "Top"
    },
    {
      "source_node": "132",
      "source_port": "Output",
      "target_node": "135",
      "target_port": "Bottom"
    },
    {
      "source_node": "134",
      "source_port": "Output",
      "target_node": "80",
      "target_port": "Input"
    },
    {
      "source_node": "83",
      "source_port": "",
      "target_node": "134",
      "target_port": "Input"
    },
    {
      "source_node": "118",
      "source_port": "Output",
      "target_node": "122",
      "target_port": "Bottom"
    },
    {
      "source_node": "119",
      "source_port": "Output",
      "target_node": "120",
      "target_port": "A"
    },
    {
      "source_node": "116",
      "source_port": "",
      "target_node": "119",
      "target_port": "Input"
    },
    {
      "source_node": "116",
      "source_port": "",
      "target_node": "118",
      "target_port": "A"
    },
    {
      "source_node": "115",
      "source_port": "",
      "target_node": "116",
      "target_port": ""
    },
    {
      "source_node": "15",
      "source_port": "B",
      "target_node": "115",
      "target_port": ""
    },
    {
      "source_node": "112",
      "source_port": "",
      "target_node": "96",
      "target_port": "Displacement"
    },
    {
      "source_node": "113",
      "source_port": "",
      "target_node": "111",
      "target_port": ""
    },
    {
      "source_node": "15",
      "source_port": "A",
      "target_node": "113",
      "target_port": ""
    },
    {
      "source_node": "114",
      "source_port": "",
      "target_node": "103",
      "target_port": "Input"
    },
    {
      "source_node": "114",
      "source_port": "",
      "target_node": "35",
      "target_port": "Input"
    },
    {
      "source_node": "78",
      "source_port": "",
      "target_node": "114",
      "target_port": ""
    },
    {
      "source_node": "56",
      "source_port": "Output",
      "target_node": "59",
      "target_port": "B"
    },
    {
      "source_node": "41",
      "source_port": "Output",
      "target_node": "59",
      "target_port": "A"
    },
    {
      "source_node": "76",
      "source_port": "",
      "target_node": "9",
      "target_port": "Displacement"
    },
    {
      "source_node": "15",
      "source_port": "R",
      "target_node": "76",
      "target_port": ""
    },
    {
      "source_node": "43",
      "source_port": "Output",
      "target_node": "75",
      "target_port": "Input"
    },
    {
      "source_node": "59",
      "source_port": "Output",
      "target_node": "42",
      "target_port": "A"
    },
    {
      "source_node": "48",
      "source_port": "Output",
      "target_node": "69",
      "target_port": "A"
    },
    {
      "source_node": "74",
      "source_port": "Output",
      "target_node": "56",
      "target_port": "Bottom"
    },
    {
      "source_node": "73",
      "source_port": "Output",
      "target_node": "74",
      "target_port": "Input"
    },
    {
      "source_node": "15",
      "source_port": "G",
      "target_node": "50",
      "target_port": ""
    },
    {
      "source_node": "49",
      "source_port": "",
      "target_node": "47",
      "target_port": "B"
    },
    {
      "source_node": "46",
      "source_port": "Output",
      "target_node": "49",
      "target_port": ""
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "47",
      "target_port": "A"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "48",
      "target_port": "Bottom"
    },
    {
      "source_node": "47",
      "source_port": "Output",
      "target_node": "48",
      "target_port": "Top"
    },
    {
      "source_node": "19",
      "source_port": "Output",
      "target_node": "30",
      "target_port": ""
    },
    {
      "source_node": "30",
      "source_port": "",
      "target_node": "29",
      "target_port": ""
    },
    {
      "source_node": "29",
      "source_port": "",
      "target_node": "28",
      "target_port": "Top"
    },
    {
      "source_node": "27",
      "source_port": "Output",
      "target_node": "28",
      "target_port": "Alpha"
    },
    {
      "source_node": "23",
      "source_port": "Output",
      "target_node": "28",
      "target_port": "Bottom"
    },
    {
      "source_node": "26",
      "source_port": "Output",
      "target_node": "27",
      "target_port": "Input"
    },
    {
      "source_node": "23",
      "source_port": "Output",
      "target_node": "25",
      "target_port": "Input"
    },
    {
      "source_node": "20",
      "source_port": "Output",
      "target_node": "23",
      "target_port": "Displacement"
    },
    {
      "source_node": "21",
      "source_port": "Output",
      "target_node": "24",
      "target_port": "Input"
    },
    {
      "source_node": "24",
      "source_port": "Output",
      "target_node": "22",
      "target_port": "Input"
    },
    {
      "source_node": "22",
      "source_port": "Output",
      "target_node": "23",
      "target_port": "Input"
    },
    {
      "source_node": "20",
      "source_port": "Output",
      "target_node": "19",
      "target_port": "Displacement"
    },
    {
      "source_node": "18",
      "source_port": "Output",
      "target_node": "19",
      "target_port": "Input"
    },
    {
      "source_node": "17",
      "source_port": "Output",
      "target_node": "18",
      "target_port": "Input"
    },
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "17",
      "target_port": "Input"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "Input"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "Flood Fill"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "Input"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Slope"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Input"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "Input"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Input"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Input"
    },
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "Input"
    },
    {
      "source_node": "25",
      "source_port": "Output",
      "target_node": "31",
      "target_port": "Flood Fill"
    },
    {
      "source_node": "31",
      "source_port": "Output",
      "target_node": "26",
      "target_port": "Input"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "39",
      "target_port": ""
    },
    {
      "source_node": "39",
      "source_port": "",
      "target_node": "38",
      "target_port": "B"
    },
    {
      "source_node": "36",
      "source_port": "Color",
      "target_node": "37",
      "target_port": "Top"
    },
    {
      "source_node": "35",
      "source_port": "Output",
      "target_node": "34",
      "target_port": "Input"
    },
    {
      "source_node": "38",
      "source_port": "Output",
      "target_node": "37",
      "target_port": "Alpha"
    },
    {
      "source_node": "34",
      "source_port": "Output",
      "target_node": "40",
      "target_port": "Input"
    },
    {
      "source_node": "40",
      "source_port": "Output",
      "target_node": "38",
      "target_port": "A"
    },
    {
      "source_node": "37",
      "source_port": "Output",
      "target_node": "41",
      "target_port": "Input"
    },
    {
      "source_node": "42",
      "source_port": "Output",
      "target_node": "43",
      "target_port": "Top"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "46",
      "target_port": "Flood Fill"
    },
    {
      "source_node": "51",
      "source_port": "Output",
      "target_node": "52",
      "target_port": "Flood Fill"
    },
    {
      "source_node": "28",
      "source_port": "Output",
      "target_node": "53",
      "target_port": "A"
    },
    {
      "source_node": "52",
      "source_port": "Output",
      "target_node": "53",
      "target_port": "B"
    },
    {
      "source_node": "28",
      "source_port": "Output",
      "target_node": "51",
      "target_port": "Input"
    },
    {
      "source_node": "53",
      "source_port": "Output",
      "target_node": "54",
      "target_port": "Input"
    },
    {
      "source_node": "28",
      "source_port": "Output",
      "target_node": "55",
      "target_port": ""
    },
    {
      "source_node": "57",
      "source_port": "Color",
      "target_node": "56",
      "target_port": "Top"
    },
    {
      "source_node": "38",
      "source_port": "Output",
      "target_node": "56",
      "target_port": "Alpha"
    },
    {
      "source_node": "50",
      "source_port": "",
      "target_node": "58",
      "target_port": ""
    },
    {
      "source_node": "58",
      "source_port": "",
      "target_node": "33",
      "target_port": "Displacement"
    },
    {
      "source_node": "58",
      "source_port": "",
      "target_node": "54",
      "target_port": "Displacement"
    },
    {
      "source_node": "55",
      "source_port": "",
      "target_node": "33",
      "target_port": "Input"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "37",
      "target_port": "Bottom"
    },
    {
      "source_node": "61",
      "source_port": "",
      "target_node": "43",
      "target_port": "Bottom"
    },
    {
      "source_node": "44",
      "source_port": "",
      "target_node": "61",
      "target_port": ""
    },
    {
      "source_node": "61",
      "source_port": "",
      "target_node": "42",
      "target_port": "B"
    },
    {
      "source_node": "62",
      "source_port": "Output",
      "target_node": "64",
      "target_port": "A"
    },
    {
      "source_node": "63",
      "source_port": "Output",
      "target_node": "64",
      "target_port": "B"
    },
    {
      "source_node": "62",
      "source_port": "Output",
      "target_node": "65",
      "target_port": "Bottom"
    },
    {
      "source_node": "64",
      "source_port": "Output",
      "target_node": "65",
      "target_port": "Top"
    },
    {
      "source_node": "65",
      "source_port": "Output",
      "target_node": "66",
      "target_port": "A"
    },
    {
      "source_node": "66",
      "source_port": "Output",
      "target_node": "67",
      "target_port": "Top"
    },
    {
      "source_node": "65",
      "source_port": "Output",
      "target_node": "67",
      "target_port": "Bottom"
    },
    {
      "source_node": "69",
      "source_port": "Output",
      "target_node": "68",
      "target_port": "Top"
    },
    {
      "source_node": "48",
      "source_port": "Output",
      "target_node": "68",
      "target_port": "Bottom"
    },
    {
      "source_node": "68",
      "source_port": "Output",
      "target_node": "44",
      "target_port": ""
    },
    {
      "source_node": "54",
      "source_port": "Output",
      "target_node": "71",
      "target_port": "A"
    },
    {
      "source_node": "72",
      "source_port": "Output",
      "target_node": "66",
      "target_port": "B"
    },
    {
      "source_node": "71",
      "source_port": "Output",
      "target_node": "73",
      "target_port": "Input"
    },
    {
      "source_node": "67",
      "source_port": "Output",
      "target_node": "77",
      "target_port": "Input"
    },
    {
      "source_node": "15",
      "source_port": "G",
      "target_node": "78",
      "target_port": ""
    },
    {
      "source_node": "78",
      "source_port": "",
      "target_node": "77",
      "target_port": "Displacement"
    },
    {
      "source_node": "77",
      "source_port": "Output",
      "target_node": "69",
      "target_port": "B"
    },
    {
      "source_node": "82",
      "source_port": "Output",
      "target_node": "81",
      "target_port": "Input"
    },
    {
      "source_node": "83",
      "source_port": "",
      "target_node": "82",
      "target_port": "Input"
    },
    {
      "source_node": "83",
      "source_port": "",
      "target_node": "79",
      "target_port": "Input"
    },
    {
      "source_node": "84",
      "source_port": "Output",
      "target_node": "85",
      "target_port": "A"
    },
    {
      "source_node": "39",
      "source_port": "",
      "target_node": "86",
      "target_port": ""
    },
    {
      "source_node": "86",
      "source_port": "",
      "target_node": "87",
      "target_port": ""
    },
    {
      "source_node": "75",
      "source_port": "Output",
      "target_node": "88",
      "target_port": "Bottom"
    },
    {
      "source_node": "85",
      "source_port": "Output",
      "target_node": "88",
      "target_port": "Top"
    },
    {
      "source_node": "89",
      "source_port": "",
      "target_node": "88",
      "target_port": "Alpha"
    },
    {
      "source_node": "90",
      "source_port": "Output",
      "target_node": "91",
      "target_port": "Input"
    },
    {
      "source_node": "91",
      "source_port": "Output",
      "target_node": "92",
      "target_port": "Input"
    },
    {
      "source_node": "92",
      "source_port": "Output",
      "target_node": "93",
      "target_port": "Input"
    },
    {
      "source_node": "93",
      "source_port": "Output",
      "target_node": "94",
      "target_port": "Input"
    },
    {
      "source_node": "94",
      "source_port": "Output",
      "target_node": "95",
      "target_port": "Input"
    },
    {
      "source_node": "95",
      "source_port": "Output",
      "target_node": "96",
      "target_port": "Input"
    },
    {
      "source_node": "96",
      "source_port": "Output",
      "target_node": "97",
      "target_port": "A"
    },
    {
      "source_node": "98",
      "source_port": "",
      "target_node": "85",
      "target_port": "B"
    },
    {
      "source_node": "87",
      "source_port": "",
      "target_node": "98",
      "target_port": ""
    },
    {
      "source_node": "98",
      "source_port": "",
      "target_node": "89",
      "target_port": ""
    },
    {
      "source_node": "99",
      "source_port": "Output",
      "target_node": "97",
      "target_port": "B"
    },
    {
      "source_node": "87",
      "source_port": "",
      "target_node": "99",
      "target_port": "Input"
    },
    {
      "source_node": "97",
      "source_port": "Output",
      "target_node": "100",
      "target_port": "A"
    },
    {
      "source_node": "101",
      "source_port": "",
      "target_node": "100",
      "target_port": "B"
    },
    {
      "source_node": "72",
      "source_port": "Output",
      "target_node": "101",
      "target_port": ""
    },
    {
      "source_node": "77",
      "source_port": "Output",
      "target_node": "102",
      "target_port": ""
    },
    {
      "source_node": "102",
      "source_port": "",
      "target_node": "71",
      "target_port": "B"
    },
    {
      "source_node": "103",
      "source_port": "Output",
      "target_node": "104",
      "target_port": "Input"
    },
    {
      "source_node": "88",
      "source_port": "Output",
      "target_node": "105",
      "target_port": "Bottom"
    },
    {
      "source_node": "104",
      "source_port": "Output",
      "target_node": "106",
      "target_port": ""
    },
    {
      "source_node": "105",
      "source_port": "Output",
      "target_node": "83",
      "target_port": ""
    },
    {
      "source_node": "99",
      "source_port": "Output",
      "target_node": "107",
      "target_port": "Input"
    },
    {
      "source_node": "107",
      "source_port": "Output",
      "target_node": "108",
      "target_port": "Input"
    },
    {
      "source_node": "108",
      "source_port": "Output",
      "target_node": "109",
      "target_port": "Top"
    },
    {
      "source_node": "100",
      "source_port": "Output",
      "target_node": "109",
      "target_port": "Bottom"
    },
    {
      "source_node": "89",
      "source_port": "",
      "target_node": "109",
      "target_port": "Alpha"
    },
    {
      "source_node": "109",
      "source_port": "Output",
      "target_node": "105",
      "target_port": "Top"
    },
    {
      "source_node": "118",
      "source_port": "Output",
      "target_node": "126",
      "target_port": "Bottom"
    },
    {
      "source_node": "125",
      "source_port": "Color",
      "target_node": "127",
      "target_port": "A"
    },
    {
      "source_node": "124",
      "source_port": "Output",
      "target_node": "127",
      "target_port": "B"
    },
    {
      "source_node": "127",
      "source_port": "Output",
      "target_node": "126",
      "target_port": "Top"
    },
    {
      "source_node": "120",
      "source_port": "Output",
      "target_node": "128",
      "target_port": "A"
    },
    {
      "source_node": "128",
      "source_port": "Output",
      "target_node": "122",
      "target_port": "Top"
    },
    {
      "source_node": "129",
      "source_port": "Output",
      "target_node": "128",
      "target_port": "B"
    },
    {
      "source_node": "124",
      "source_port": "Output",
      "target_node": "129",
      "target_port": "Input"
    },
    {
      "source_node": "121",
      "source_port": "Color",
      "target_node": "130",
      "target_port": "A"
    },
    {
      "source_node": "123",
      "source_port": "Output",
      "target_node": "130",
      "target_port": "B"
    },
    {
      "source_node": "130",
      "source_port": "Output",
      "target_node": "120",
      "target_port": "B"
    },
    {
      "source_node": "117",
      "source_port": "Color",
      "target_node": "131",
      "target_port": "A"
    },
    {
      "source_node": "131",
      "source_port": "Output",
      "target_node": "118",
      "target_port": "B"
    },
    {
      "source_node": "123",
      "source_port": "Output",
      "target_node": "131",
      "target_port": "B"
    },
    {
      "source_node": "122",
      "source_port": "Output",
      "target_node": "132",
      "target_port": "Input"
    },
    {
      "source_node": "133",
      "source_port": "Output",
      "target_node": "110",
      "target_port": "Input"
    },
    {
      "source_node": "141",
      "source_port": "Output",
      "target_node": "149",
      "target_port": "A"
    },
    {
      "source_node": "148",
      "source_port": "Output",
      "target_node": "149",
      "target_port": "B"
    },
    {
      "source_node": "149",
      "source_port": "Output",
      "target_node": "135",
      "target_port": "Alpha"
    },
    {
      "source_node": "150",
      "source_port": "",
      "target_node": "143",
      "target_port": "Alpha"
    },
    {
      "source_node": "149",
      "source_port": "Output",
      "target_node": "150",
      "target_port": ""
    },
    {
      "source_node": "153",
      "source_port": "",
      "target_node": "136",
      "target_port": ""
    },
    {
      "source_node": "123",
      "source_port": "Output",
      "target_node": "154",
      "target_port": ""
    },
    {
      "source_node": "154",
      "source_port": "",
      "target_node": "153",
      "target_port": ""
    },
    {
      "source_node": "114",
      "source_port": "",
      "target_node": "155",
      "target_port": ""
    },
    {
      "source_node": "155",
      "source_port": "",
      "target_node": "156",
      "target_port": ""
    },
    {
      "source_node": "156",
      "source_port": "",
      "target_node": "122",
      "target_port": "Alpha"
    },
    {
      "source_node": "147",
      "source_port": "",
      "target_node": "148",
      "target_port": "Input"
    },
    {
      "source_node": "111",
      "source_port": "",
      "target_node": "112",
      "target_port": ""
    },
    {
      "source_node": "134",
      "source_port": "Output",
      "target_node": "133",
      "target_port": "A"
    },
    {
      "source_node": "135",
      "source_port": "Output",
      "target_node": "133",
      "target_port": "B"
    },
    {
      "source_node": "124",
      "source_port": "Output",
      "target_node": "159",
      "target_port": ""
    },
    {
      "source_node": "159",
      "source_port": "",
      "target_node": "126",
      "target_port": "Alpha"
    }
  ]
}