{
  "nodes": [
    {
      "id": "0",
      "type": "ShapeNode",
      "title": "Shape",
      "x": -300.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Gaussian",
        "size": 0.7,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "RotateScaleNode",
      "title": "Rotate Scale",
      "x": -100.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "angle": 0.0,
        "scale_x": 0.2,
        "scale_y": 1.2
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "ScatterNode",
      "title": "Scatter",
      "x": 100.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "count": 200,
        "scale": 0.4,
        "scale_variance": 0.3,
        "rotation_variance": 10.0,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "CloudsNode",
      "title": "Clouds",
      "x": 800.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 128.0,
        "octaves": 4,
        "persistence": 0.6,
        "contrast": 1.5,
        "seed": 0
      },
      "promoted_fields": [
        "scale"
      ]
    },
    {
      "id": "4",
      "type": "PerlinNoiseNode",
      "title": "Perlin Noise",
      "x": 1000.0,
      "y": -500.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 256.0,
        "octaves": 1,
        "seed": 0
      },
      "promoted_fields": [
        "scale"
      ]
    },
    {
      "id": "5",
      "type": "DirectionalWarpNode",
      "title": "Directional Warp",
      "x": 1000.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 400.0,
        "direction": 90.0
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 1200.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "BlurNode",
      "title": "Blur",
      "x": 300.0,
      "y": 20.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 10.0
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 500.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "WarpNode",
      "title": "Warp",
      "x": 1100.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 30.0,
        "direction": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 700.0,
      "y": -40.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "HistogramScanNode",
      "title": "Histogram Scan",
      "x": 900.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "position": 1.0,
        "contrast": 0.5
      },
      "promoted_fields": [
        "position"
      ]
    },
    {
      "id": "12",
      "type": "CloudsNode",
      "title": "Clouds",
      "x": 300.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "scale": 128.0,
        "octaves": 4,
        "persistence": 0.6,
        "contrast": 1.5,
        "seed": 0
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 500.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 100,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "WarpNode",
      "title": "Warp",
      "x": 900.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 100.0,
        "direction": 270.0
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "DirectionalWarpNode",
      "title": "Directional Warp",
      "x": 700.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 100.0,
        "direction": 45.0
      },
      "promoted_fields": []
    },
    {
      "id": "16",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1100.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "17",
      "type": "TileNode",
      "title": "Tile",
      "x": 1300.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "tiles_x": 2,
        "tiles_y": 1
      },
      "promoted_fields": []
    },
    {
      "id": "18",
      "type": "InvertNode",
      "title": "Invert",
      "x": 900.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "19",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 255,
        "output_low": 0,
        "output_high": 100,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "20",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 1300.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "21",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 1500.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "22",
      "type": "OffsetNode",
      "title": "Offset",
      "x": 1500.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "offset_x": 512,
        "offset_y": 0,
        "wrap": true
      },
      "promoted_fields": []
    },
    {
      "id": "23",
      "type": "WarpNode",
      "title": "Warp",
      "x": 1700.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "strength": 50.0,
        "direction": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "24",
      "type": "ColorNode",
      "title": "Color",
      "x": 1740.0,
      "y": 160.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          149,
          149,
          149,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "25",
      "type": "OverlayNode",
      "title": "Overlay",
      "x": 1900.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "mix": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "26",
      "type": "MaxNode",
      "title": "Max",
      "x": 2100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "27",
      "type": "RerouteNode",
      "title": "",
      "x": 2040.0,
      "y": -280.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "28",
      "type": "InvertNode",
      "title": "Invert",
      "x": 2300.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "29",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": 700.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Position",
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "30",
      "type": "RerouteNode",
      "title": "",
      "x": 1000.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "31",
      "type": "RerouteNode",
      "title": "",
      "x": 1600.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "32",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": 200.0,
      "y": -500.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Scale",
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "33",
      "type": "DivideNode",
      "title": "Divide",
      "x": 400.0,
      "y": -300.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "34",
      "type": "FloatNode",
      "title": "Float",
      "x": 200.0,
      "y": -280.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 2.0
      },
      "promoted_fields": []
    },
    {
      "id": "35",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 2500.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "28",
      "source_port": "Output",
      "target_node": "35",
      "target_port": "Output"
    },
    {
      "source_node": "33",
      "source_port": "Output",
      "target_node": "3",
      "target_port": "scale"
    },
    {
      "source_node": "32",
      "source_port": "Scale",
      "target_node": "4",
      "target_port": "scale"
    },
    {
      "source_node": "34",
      "source_port": "Output",
      "target_node": "33",
      "target_port": "B"
    },
    {
      "source_node": "32",
      "source_port": "Scale",
      "target_node": "33",
      "target_port": "A"
    },
    {
      "source_node": "17",
      "source_port": "Output",
      "target_node": "22",
      "target_port": "Input"
    },
    {
      "source_node": "17",
      "source_port": "Output",
      "target_node": "21",
      "target_port": "B"
    },
    {
      "source_node": "20",
      "source_port": "Output",
      "target_node": "21",
      "target_port": "A"
    },
    {
      "source_node": "19",
      "source_port": "Output",
      "target_node": "20",
      "target_port": "B"
    },
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "20",
      "target_port": "A"
    },
    {
      "source_node": "18",
      "source_port": "Output",
      "target_node": "19",
      "target_port": "Input"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "18",
      "target_port": "Input"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "17",
      "target_port": "Input"
    },
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "16",
      "target_port": "Input"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "Displacement"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "Input"
    },
    {
      "source_node": "13",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "Displacement"
    },
    {
      "source_node": "13",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "Input"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "Input"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "Input"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "A"
    },
    {
      "source_node": "7",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "B"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "7",
      "target_port": "Input"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Displacement"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "Input"
    },
    {
      "source_node": "0",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "2",
      "target_port": "Input"
    },
    {
      "source_node": "22",
      "source_port": "Output",
      "target_node": "23",
      "target_port": "Input"
    },
    {
      "source_node": "21",
      "source_port": "Output",
      "target_node": "25",
      "target_port": "Bottom"
    },
    {
      "source_node": "24",
      "source_port": "Color",
      "target_node": "25",
      "target_port": "Top"
    },
    {
      "source_node": "23",
      "source_port": "Output",
      "target_node": "25",
      "target_port": "Alpha"
    },
    {
      "source_node": "25",
      "source_port": "Output",
      "target_node": "26",
      "target_port": "B"
    },
    {
      "source_node": "27",
      "source_port": "",
      "target_node": "26",
      "target_port": "A"
    },
    {
      "source_node": "26",
      "source_port": "Output",
      "target_node": "28",
      "target_port": "Input"
    },
    {
      "source_node": "29",
      "source_port": "Position",
      "target_node": "11",
      "target_port": "position"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "30",
      "target_port": ""
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Input"
    },
    {
      "source_node": "31",
      "source_port": "",
      "target_node": "23",
      "target_port": "Displacement"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "A"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "B"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "27",
      "target_port": ""
    },
    {
      "source_node": "30",
      "source_port": "",
      "target_node": "31",
      "target_port": ""
    },
    {
      "source_node": "30",
      "source_port": "",
      "target_node": "9",
      "target_port": "Displacement"
    }
  ]
}