{
  "nodes": [
    {
      "id": "0",
      "type": "ResolutionNode",
      "title": "Resolution",
      "x": -500.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "DivideNode",
      "title": "Divide",
      "x": 100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "MinNode",
      "title": "Min",
      "x": -300.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "FloatNode",
      "title": "Float",
      "x": -300.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 8.0
      },
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "BlurNode",
      "title": "Blur",
      "x": 300.0,
      "y": -100.0,
      "width": null,
      "height": null,
      "fields": {
        "radius": 16.0
      },
      "promoted_fields": [
        "radius"
      ]
    },
    {
      "id": "5",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 520.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 520.0,
      "y": -120.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "RerouteNode",
      "title": "",
      "x": 400.0,
      "y": -180.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 700.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "NormalizeNode",
      "title": "Normalize",
      "x": 700.0,
      "y": -120.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 900.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 1500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -500.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Input",
        "data_type": "vector4",
        "default_value": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "DivideNode",
      "title": "Divide",
      "x": -100.0,
      "y": 60.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "float"
      },
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1300.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 200,
        "input_high": 255,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "LevelsNode",
      "title": "Levels",
      "x": 1100.0,
      "y": -200.0,
      "width": null,
      "height": null,
      "fields": {
        "input_low": 0,
        "input_high": 20,
        "output_low": 0,
        "output_high": 255,
        "gamma": 1.0
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Output"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "15",
      "target_port": "Input"
    },
    {
      "source_node": "15",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "Input"
    },
    {
      "source_node": "1",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "radius"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "A"
    },
    {
      "source_node": "0",
      "source_port": "X",
      "target_node": "2",
      "target_port": "A"
    },
    {
      "source_node": "0",
      "source_port": "Y",
      "target_node": "2",
      "target_port": "B"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "B"
    },
    {
      "source_node": "7",
      "source_port": "",
      "target_node": "5",
      "target_port": "A"
    },
    {
      "source_node": "7",
      "source_port": "",
      "target_node": "6",
      "target_port": "B"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "6",
      "target_port": "A"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "8",
      "target_port": "Input"
    },
    {
      "source_node": "6",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "8",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "A"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "10",
      "target_port": "B"
    },
    {
      "source_node": "12",
      "source_port": "Input",
      "target_node": "0",
      "target_port": "Input"
    },
    {
      "source_node": "12",
      "source_port": "Input",
      "target_node": "7",
      "target_port": ""
    },
    {
      "source_node": "12",
      "source_port": "Input",
      "target_node": "4",
      "target_port": "Input"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "A"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "B"
    },
    {
      "source_node": "13",
      "source_port": "Output",
      "target_node": "1",
      "target_port": "B"
    }
  ]
}