{
  "nodes": [
    {
      "id": "0",
      "type": "ShapeNode",
      "title": "Shape",
      "x": -2300.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Circle",
        "size": 0.7,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "1",
      "type": "ShapeNode",
      "title": "Shape",
      "x": -2300.0,
      "y": 260.0,
      "width": null,
      "height": null,
      "fields": {
        "shape": "Gaussian",
        "size": 0.5,
        "rotation": 0.0
      },
      "promoted_fields": []
    },
    {
      "id": "2",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": -1700.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "3",
      "type": "FloatToVec4Node",
      "title": "Float to Vec4",
      "x": -1540.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "4",
      "type": "AddNode",
      "title": "Add",
      "x": -1400.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "5",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": -1100.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "6",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -1700.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Offset",
        "data_type": "float",
        "default_value": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "7",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -800.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Sharpness",
        "data_type": "float",
        "default_value": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "8",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -1740.0,
      "y": -40.0,
      "width": 840,
      "height": 200,
      "fields": {
        "label": "Difference",
        "color": [
          80,
          80,
          40,
          180
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "9",
      "type": "FloatToVec4Node",
      "title": "Float to Vec4",
      "x": -1240.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "10",
      "type": "FloatNode",
      "title": "Float",
      "x": -1380.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "11",
      "type": "ClampNode",
      "title": "Clamp",
      "x": 0.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4",
        "minimum": 0.0,
        "maximum": 1.0
      },
      "promoted_fields": []
    },
    {
      "id": "12",
      "type": "FloatNode",
      "title": "Float",
      "x": -500.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {
        "value": 0.5
      },
      "promoted_fields": []
    },
    {
      "id": "13",
      "type": "FloatToVec4Node",
      "title": "Float to Vec4",
      "x": -360.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "14",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": -500.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "15",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -2100.0,
      "y": -140.0,
      "width": 300,
      "height": 60,
      "fields": {
        "label": "weight = clamp(diff * sharpness + 0.5, 0, 1)",
        "color": [
          62,
          37,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "16",
      "type": "FloatToVec4Node",
      "title": "Float to Vec4",
      "x": -640.0,
      "y": 80.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "17",
      "type": "AddNode",
      "title": "Add",
      "x": -200.0,
      "y": 0.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "18",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -2100.0,
      "y": -60.0,
      "width": 300,
      "height": 60,
      "fields": {
        "label": "result = bottom * (1 - weight) + top * weight",
        "color": [
          62,
          37,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "19",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -840.0,
      "y": -40.0,
      "width": 1040,
      "height": 200,
      "fields": {
        "label": "Weight",
        "color": [
          80,
          80,
          40,
          180
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "20",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -2100.0,
      "y": -300.0,
      "width": 240,
      "height": 60,
      "fields": {
        "label": "dif = top - bottom",
        "color": [
          62,
          37,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "21",
      "type": "CatenaCommentBox",
      "title": "Comment",
      "x": -2100.0,
      "y": -220.0,
      "width": 240,
      "height": 60,
      "fields": {
        "label": "diff = diff + height_offset - 0.5",
        "color": [
          62,
          37,
          80,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "22",
      "type": "ColorNode",
      "title": "Color",
      "x": 100.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "color": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "23",
      "type": "SubtractNode",
      "title": "Subtract",
      "x": 300.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "24",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 500.0,
      "y": 300.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "25",
      "type": "RerouteNode",
      "title": "",
      "x": -1800.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "26",
      "type": "RerouteNode",
      "title": "",
      "x": 400.0,
      "y": 400.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "27",
      "type": "MultiplyNode",
      "title": "Multiply",
      "x": 500.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "28",
      "type": "RerouteNode",
      "title": "",
      "x": -1800.0,
      "y": 220.0,
      "width": null,
      "height": null,
      "fields": {},
      "promoted_fields": []
    },
    {
      "id": "29",
      "type": "AddNode",
      "title": "Add",
      "x": 700.0,
      "y": 240.0,
      "width": null,
      "height": null,
      "fields": {
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "30",
      "type": "GraphOutputNode",
      "title": "Graph Output",
      "x": 900.0,
      "y": 240.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Output",
        "data_type": "vector4"
      },
      "promoted_fields": []
    },
    {
      "id": "31",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -2100.0,
      "y": 100.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Top",
        "data_type": "vector4",
        "default_value": [
          255,
          255,
          255,
          255
        ]
      },
      "promoted_fields": []
    },
    {
      "id": "32",
      "type": "GraphInputNode",
      "title": "Graph Input",
      "x": -2100.0,
      "y": 200.0,
      "width": null,
      "height": null,
      "fields": {
        "name": "Bottom",
        "data_type": "vector4",
        "default_value": [
          0,
          0,
          0,
          255
        ]
      },
      "promoted_fields": []
    }
  ],
  "wires": [
    {
      "source_node": "32",
      "source_port": "Bottom",
      "target_node": "25",
      "target_port": ""
    },
    {
      "source_node": "32",
      "source_port": "Bottom",
      "target_node": "2",
      "target_port": "B"
    },
    {
      "source_node": "31",
      "source_port": "Top",
      "target_node": "28",
      "target_port": ""
    },
    {
      "source_node": "31",
      "source_port": "Top",
      "target_node": "2",
      "target_port": "A"
    },
    {
      "source_node": "29",
      "source_port": "Output",
      "target_node": "30",
      "target_port": "Output"
    },
    {
      "source_node": "24",
      "source_port": "Output",
      "target_node": "29",
      "target_port": "B"
    },
    {
      "source_node": "27",
      "source_port": "Output",
      "target_node": "29",
      "target_port": "A"
    },
    {
      "source_node": "28",
      "source_port": "",
      "target_node": "27",
      "target_port": "A"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "27",
      "target_port": "B"
    },
    {
      "source_node": "26",
      "source_port": "",
      "target_node": "24",
      "target_port": "B"
    },
    {
      "source_node": "25",
      "source_port": "",
      "target_node": "26",
      "target_port": ""
    },
    {
      "source_node": "23",
      "source_port": "Output",
      "target_node": "24",
      "target_port": "A"
    },
    {
      "source_node": "11",
      "source_port": "Output",
      "target_node": "23",
      "target_port": "B"
    },
    {
      "source_node": "22",
      "source_port": "Color",
      "target_node": "23",
      "target_port": "A"
    },
    {
      "source_node": "5",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "A"
    },
    {
      "source_node": "6",
      "source_port": "Offset",
      "target_node": "3",
      "target_port": "Input"
    },
    {
      "source_node": "4",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "A"
    },
    {
      "source_node": "3",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "B"
    },
    {
      "source_node": "2",
      "source_port": "Output",
      "target_node": "4",
      "target_port": "A"
    },
    {
      "source_node": "9",
      "source_port": "Output",
      "target_node": "5",
      "target_port": "B"
    },
    {
      "source_node": "10",
      "source_port": "Output",
      "target_node": "9",
      "target_port": "Input"
    },
    {
      "source_node": "7",
      "source_port": "Sharpness",
      "target_node": "16",
      "target_port": "Input"
    },
    {
      "source_node": "16",
      "source_port": "Output",
      "target_node": "14",
      "target_port": "B"
    },
    {
      "source_node": "12",
      "source_port": "Output",
      "target_node": "13",
      "target_port": "Input"
    },
    {
      "source_node": "14",
      "source_port": "Output",
      "target_node": "17",
      "target_port": "A"
    },
    {
      "source_node": "13",
      "source_port": "Output",
      "target_node": "17",
      "target_port": "B"
    },
    {
      "source_node": "17",
      "source_port": "Output",
      "target_node": "11",
      "target_port": "Input"
    }
  ]
}
